name: test-py6s
on: [push]
jobs:
  example-4:
    name: Test Py6S
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.7
          channels: conda-forge
      - run: |
          conda install py6s
          python -c "from Py6S import *; SixS.test()"