name: learn-github-actions
on: [push]
jobs:
  test:
    name: Ex4 Linux
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v2
        - uses: conda-incubator/setup-miniconda@v1
          with:
            python-version: 3.7
            channels: conda-forge,
        - run: |
            conda info
            conda list
            conda config --show-sources
            conda config --show