name: test-py6s
on: [push]
jobs:
  test-py6s:
    name: Test Py6S
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.7
          channels: conda-forge
          activate-environment: py6s-test
      - shell: bash -l {0}
        run: |
          conda install py6s
      - shell: bash -l {0}
        run: python -c "from Py6S import *; SixS.test()"